AnswerMeThis/AnswerMeThis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]

AnswerMeThis/accounts/urls.py
from django.conf.urls import url
from . import views
import django.contrib.auth.views as auth_views

urlpatterns = [
    url(r'^$', views.register, name='register'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^ask/', views.ask, name='ask'),
    url(r'^user/(?P<username>\w+)/(?P<question>\w+)/(?P<oneortwo>\w+)', views.get_question, name='2get_question'),
    url(r'^user/(?P<username>\w+)/(?P<question>\w+)', views.get_question, name='get_question'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {"next_page":".."}),



]

AnswerMeThis/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    question = models.CharField(max_length=250)
    option1 = models.CharField(max_length=100)
    option2 = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    option1_votes = models.IntegerField(default=0)
    no_of_votes = models.IntegerField(default=0)
    link = models.CharField(max_length=500)

    def __str__(self):
        return self.question

AnswerMeThis/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Question

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class AskQuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ('question', 'option1', 'option2')

AnswerMeThis/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from .forms import SignUpForm, AskQuestionForm
from .models import Question

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            print('logged in')
            return redirect('/../accounts/profile/')

    else:
        form = SignUpForm()
    return render(request, 'accounts/register.html', {'form':form})



def profile(request):
    if request.user.is_authenticated():
        user = User.objects.get(username=request.user.username)
        question_objects = Question.objects.filter(author=user)
        questions = []
        for question in question_objects:
            _question = question.question
            Option1 = question.option1
            try:
                Option1_percentage = (question.option1_votes / question.no_of_votes) * 100
            except:
                Option1_percentage = 0
            Option2 = question.option2
            Option2_percentage = 100 - Option1_percentage
            No_of_votes = question.no_of_votes

            if No_of_votes == 0:
                state1 = 'minority'
                state2 = 'minority'
                Option2_percentage = 0
            elif Option1_percentage > Option2_percentage:
                state1 = 'majority'
                state2 = 'minority'
            elif Option1_percentage < Option2_percentage:
                state1 = 'minority'
                state2 = 'majority'
            else:
                state1 = 'majority'
                state2 = 'majority'

            questions.append([_question, Option1, state1, Option1_percentage, Option2, state2, Option2_percentage, No_of_votes])

        return render(request, 'accounts/profile.html', {'questions': questions})
    #add redirect to sign up page

def ask(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = AskQuestionForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                question = post.question.replace(' ', '')
                question = question.replace('/', '')
                question = question.replace('?', '')
                post.link = question
                post.save()
                #form.save()
                return redirect('/../accounts/profile/')

        else:
            form = AskQuestionForm()
        return render(request, 'accounts/ask.html', {'form':form})
    else:
        return redirect("../")

def get_question(request, username, question, oneortwo = None):
    if request.method == 'POST':
        u = request.session['u']
        q = request.session['q']
        print('u: ' + u)
        print('q: ' + q)
        print(username)
        print(question)
        print(oneortwo)


        u = User.objects.get(username=u)
        list_of_user_questions = Question.objects.filter(author=u)
        for _question in list_of_user_questions:
            #print(_question)
            if _question.link == question:
                print('QUESTION FOUND FOR LOOP POST get_question')
                q = _question
                break

        if oneortwo == "one":
            print('one')
            q.no_of_votes += 1
            q.option1_votes += 1

        elif oneortwo == "two":
            q.no_of_votes += 1

        elif oneortwo is None:
            print('ELSE @@')

        q.save()
        Option1_percentage = (q.option1_votes / q.no_of_votes) * 100
        Option2_percentage = 100 - Option1_percentage

        if Option1_percentage > Option2_percentage:
            state1 = 'majority'
            state2 = 'minority'
        elif Option1_percentage < Option2_percentage:
            state1 = 'minority'
            state2 = 'majority'
        else:
            state1 = 'majority'
            state2 = 'majority'

        request.session['q'] = ''
        request.session['u'] = ''
        return render(request, "accounts/results.html", {'question': [q.question, q.option1, state1, Option1_percentage, q.option2, state2, Option2_percentage]})
    else:
        try:
            u = User.objects.get(username=username)
            print('got user')
            print(u)
        except:
            print("except username")

        try:
            list_of_user_questions = Question.objects.filter(author=u)
            for _question in list_of_user_questions:
                print(_question)
                if _question.link == question:
                    print(_question)
                    q = _question
                    print('found q: ' + q)
                    break
        except:
            print("except question")

        form_question = q.question
        option1 = q.option1
        option2 = q.option2

        request.session['u'] = u.username
        request.session['q'] = q.question

        return render(request, 'accounts/answer.html', {'question': [form_question, option1, option2, q.link]})

AnswerMeThis/accounts/templates/accounts/answer.html
{% extends "accounts/base.html" %}

{% block content %}

<br>
<br>
<center>
  <div class="box">
    <p class='question'><b>Question:</b> {{question.0}}</p>

    <br>
    
    <form action="{{question.3}}/one" method="post" >
      {% csrf_token %}
      <div name ='action' value='submit-form1' onClick="javascript: this.parentNode.submit();" class="majority">
        <p><b>Option 1:</b> {{question.1}}</p>
      </div>
    </form>

    <br>

    <form action="{{question.3}}/two" method="post">
      {% csrf_token %}
      <div name='action' value='submit-form2' onClick="javascript: this.parentNode.submit();" class="majority">
        <p><b>Option 2:</b> {{question.2}}</p>
      </div>
    </form>
  </div>
</center>

{% endblock %}

AnswerMeThis/accounts/templates/accounts/ask.html
{% extends "accounts/base.html" %}

{% block content %}
<center style="padding: 50px;">
  <h1>Ask a question</h1>
  <form method='post' style="padding:30px;">
    {% csrf_token %}
    {{form.as_p}}
    {{profile_form.as_p}}
    <button type="submit" class='btn btn-primary'>Ask Question</button>
  </form
</center>
{% endblock %}

AnswerMeThis/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <meta name='viewport' content="width=device-width, initial-scale=1.0"/>
  <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}" type = "text/css"/>
  <link rel="icon" type="image/png" href={% static 'accounts/images/AnswerMeThis.png' %}/>
  <title>Answer Me This</title>

  <style type="text/css">
    .profile{
      margin-top: 60px;
      padding: 20px;
      margin-bottom: 10px;
      margin-right: 60px;
    }


    .box{
      margin-right: 300px;
      display: inline;
    }

    .question, #id_question{
      border: black 2px solid;
      border-radius: 5px;
      padding: 10px;
      background: linear-gradient(to right, #ffdb26dd, #ffff00dd);
      position: relative;
      margin-bottom: 20px;
    }

    #id_option1, #id_option2{
      border: black 2px solid;
      border-radius: 5px;
      padding: 10px;
      background: linear-gradient(to right, #99ee13dd, #00ff00dd);
      position: relative;
      margin-bottom: 20px;
    }

    .majority{
      border: black 2px solid;
      border-radius: 5px;
      padding: 10px;
      background: linear-gradient(to right, #99ee13dd, #00ff00dd);
      position: relative;
      margin-bottom: 20px;
    }

    .minority{
      border: black 2px solid;
      border-radius: 5px;
      padding:10px;
      background: linear-gradient(to right, #ee2727dd, #ff0000dd);
      position: relative;
      margin-bottom: 20px;
    }

    .percentage{
      position: absolute;
      bottom: -10px;
      right: 16px;
      font-size: 16px;
    }

    .ask{
      position: absolute;
      top: 25px;
      right: 50px;
      font-size: 18px;
    }

    .site-form{
      margin-top: 60px;
      border: 2px solid #00dba0;
      padding: 20px;
      margin-bottom: 10px;
    }

    .site-form input{
      display: block;
      margin: 20px 0 0 0;
      padding: 10px;
    }

    .helptext, .helptext ul{
      margin: 0 auto 20px;
      color: #bbb;
      font-size: 0.9em;
      display: block;
    }

    .errorlist li{
      padding: 7px;
      list-style-type: none;
      border:1px solid #ff5722;
      margin 10px 1px;
    }

    .errorlist{
      padding: 0px;
    }

    {% block styles %}
    {% endblock %}

  </style>

</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

AnswerMeThis/accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}


{% block content %}



  <div class="profile">
    <center>
      <h1>Profile</h1>
      <h3>Your Questions:</h3>
      <h6>Click <a href='../logout'>here</a> to log out</h6>
    </center>

    <a href='../ask'><button class='btn btn-primary ask'>ask</button></a>

    {% for question in questions %}
      <div class="box">
        <p class='question'><b>Question:</b> {{question.0}}</p>

        <div class="{{question.2}}">
          <p><b>Option 1:</b> {{question.1}}</p>
          <p class='percentage'><b> <i> {{question.3}}% </i> </b></p>
        </div>

        <div class="{{question.5}}">
          <p><b>Option 2:</b> {{question.4}}</p>
          <p class='percentage'><b> <i> {{question.6}}% </i> </b></p>
        </div>

        <h6>Number of votes: {{question.7}}</h6>
        <h6>Question Link: {{question.8}} (Share this link with your friends so they can vote!)</h6>
      </div>
      <br>
      {% endfor %}


  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>


{% endblock %}

AnswerMeThis/accounts/templates/accounts/register.html
{% extends "accounts/base.html" %}

{% block content %}
<br>
<center>
  <h1>Sign up:</h1>
  <h4>Alreday have an account? Click <a href='login'>here</a></h4>
  <form method='post' class='site-form'>
    {% csrf_token %}
    {{form.as_p}}
    {{profile_form.as_p}}
    <button type="submit" class='btn btn-primary'>Sign Up</button>
  </form
</center>
{% endblock %}

AnswerMeThis/accounts/templates/accounts/results.html
{% extends "accounts/base.html" %}

{% block content %}

<br>
<br>
<center>
  <div class="box">
    <p class='question'><b>Question:</b> {{question.0}}</p>

    <br>

    <div class="{{question.2}}">
      <p><b>Option 1:</b> {{question.1}}</p>
      <p class='percentage'><b> <i> {{question.3}}% </i> </b></p>
    </div>

    <br>

    <div class="{{question.5}}">
      <p><b>Option 2:</b> {{question.4}}</p>
      <p class='percentage'><b> <i> {{question.6}}% </i> </b></p>
    </div>
  </div>
</center>

{% endblock %}